-- Seed proxy_templates for production
-- These were previously only in seed.sql (local dev only)

INSERT INTO proxy_templates (name, slug, description, icon, category, target_url, http_method, target_headers, secret_hints, pass_through_body, sort_order)
VALUES
    ('Brevo', 'brevo', 'Send transactional emails via the Brevo (formerly Sendinblue) API', 'lucide:mail', 'email', 'https://api.brevo.com/v3/smtp/email', 'POST', '{"Content-Type": "application/json", "Accept": "application/json"}', '[{"inject_as": "header", "key": "api-key", "variable_name_hint": "BREVO_API_KEY"}]', true, 0),
    ('Stripe', 'stripe', 'Create charges and manage payments via the Stripe API', 'lucide:credit-card', 'payment', 'https://api.stripe.com/v1/charges', 'POST', '{"Content-Type": "application/x-www-form-urlencoded"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "STRIPE_SECRET_KEY"}]', true, 1),
    ('OpenAI', 'openai', 'Send chat completion requests to the OpenAI API', 'lucide:brain', 'ai', 'https://api.openai.com/v1/chat/completions', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "OPENAI_API_KEY"}]', true, 2),
    ('SendGrid', 'sendgrid', 'Send transactional emails via the Twilio SendGrid API', 'lucide:send', 'email', 'https://api.sendgrid.com/v3/mail/send', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "SENDGRID_API_KEY"}]', true, 3),
    ('Resend', 'resend', 'Send transactional emails via the Resend API', 'lucide:mail-plus', 'email', 'https://api.resend.com/emails', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "RESEND_API_KEY"}]', true, 4),
    ('Postmark', 'postmark', 'Send transactional emails via the Postmark API', 'lucide:mail-check', 'email', 'https://api.postmarkapp.com/email', 'POST', '{"Content-Type": "application/json", "Accept": "application/json"}', '[{"inject_as": "header", "key": "X-Postmark-Server-Token", "variable_name_hint": "POSTMARK_SERVER_TOKEN"}]', true, 5),
    ('Anthropic Claude', 'anthropic', 'Send messages to the Anthropic Claude API', 'lucide:bot', 'ai', 'https://api.anthropic.com/v1/messages', 'POST', '{"Content-Type": "application/json", "anthropic-version": "2023-06-01"}', '[{"inject_as": "header", "key": "x-api-key", "variable_name_hint": "ANTHROPIC_API_KEY"}]', true, 6),
    ('Mistral', 'mistral', 'Send chat completion requests to the Mistral AI API', 'lucide:wind', 'ai', 'https://api.mistral.ai/v1/chat/completions', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "MISTRAL_API_KEY"}]', true, 7),
    ('Groq', 'groq', 'Send chat completion requests to the Groq API (OpenAI-compatible)', 'lucide:zap', 'ai', 'https://api.groq.com/openai/v1/chat/completions', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "GROQ_API_KEY"}]', true, 8),
    ('Paddle', 'paddle', 'Create transactions via the Paddle billing API', 'lucide:receipt', 'payment', 'https://api.paddle.com/transactions', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "PADDLE_API_KEY"}]', true, 9),
    ('LemonSqueezy', 'lemonsqueezy', 'Create checkouts via the Lemon Squeezy API', 'lucide:shopping-cart', 'payment', 'https://api.lemonsqueezy.com/v1/checkouts', 'POST', '{"Content-Type": "application/vnd.api+json", "Accept": "application/vnd.api+json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "LEMONSQUEEZY_API_KEY"}]', true, 10),
    ('Mollie', 'mollie', 'Create payments via the Mollie API', 'lucide:wallet', 'payment', 'https://api.mollie.com/v2/payments', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "MOLLIE_API_KEY"}]', true, 11),
    ('Intercom', 'intercom', 'Send messages and create conversations via the Intercom API', 'lucide:message-circle', 'support', 'https://api.intercom.io/messages', 'POST', '{"Content-Type": "application/json", "Intercom-Version": "2.15"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "INTERCOM_ACCESS_TOKEN"}]', true, 12),
    ('HubSpot', 'hubspot', 'Create contacts and manage CRM objects via the HubSpot API', 'lucide:users', 'crm', 'https://api.hubapi.com/crm/v3/objects/contacts', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Bearer ${value}", "variable_name_hint": "HUBSPOT_ACCESS_TOKEN"}]', true, 13),
    ('OneSignal', 'onesignal', 'Send push notifications via the OneSignal API', 'lucide:bell', 'notifications', 'https://api.onesignal.com/notifications', 'POST', '{"Content-Type": "application/json"}', '[{"inject_as": "header", "key": "Authorization", "template": "Key ${value}", "variable_name_hint": "ONESIGNAL_REST_API_KEY"}]', true, 14)
ON CONFLICT (slug) DO NOTHING;
